services:
  gateway:
    image: ghcr.io/ardatan/hive-gateway:1.3.0-alpha-20241017125345-a7d48a35da53f60da5f14745845de70dd5e06e7a
    container_name: gateway
    networks:
      - test
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      - NODE_ENV=production
      - JIT=1
      - FORK=2
    depends_on:
      accounts:
        condition: service_healthy
      inventory:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy
    volumes:
      - type: bind
        source: federation-v1/gateways/hive-gateway/supergraph.graphql
        target: /serve/supergraph.graphql
    healthcheck:
      test:
        [
          "CMD",
          "/usr/lib/apt/apt-helper",
          "download-file",
          "http://127.0.0.1:4000/readiness",
          "/tmp/health",
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    command: ["supergraph"]
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-1gb}
networks:
  test:
    name: test
