sources:
  - name: accounts
    handler:
      graphql:
        endpoint: http://accounts:4001/graphql
        source: ./accounts.graphql
  - name: inventory
    handler:
      graphql:
        endpoint: http://inventory:4002/graphql
        source: ./inventory.graphql
  - name: products
    handler:
      graphql:
        endpoint: http://products:4003/graphql
        source: ./products.graphql
  - name: reviews
    handler:
      graphql:
        endpoint: http://reviews:4004/graphql
        source: ./reviews.graphql

serve:
  fork: true