sources:
  - name: accounts
    handler:
      graphql:
        endpoint: http://accounts:4001/graphql
  - name: inventory
    handler:
      graphql:
        endpoint: http://inventory:4002/graphql
  - name: products
    handler:
      graphql:
        endpoint: http://products:4003/graphql
  - name: reviews
    handler:
      graphql:
        endpoint: http://reviews:4004/graphql

serve:
  fork: true