version: '3.8'

services:
  users:
    image: '${DOCKER_REGISTRY}subgraph-v2-users${DOCKER_TAG}'
    container_name: v2-users
    networks:
      - test
    ports:
      - "0.0.0.0:4001:4001"
    environment:
      APOLLO_PORT: 4001
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4001/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
      interval: 3s
      timeout: 5s
      retries: 10
  inventory:
    image: '${DOCKER_REGISTRY}subgraph-v2-inventory${DOCKER_TAG}'
    container_name: v2-inventory
    networks:
      - test
    ports:
      - 4002:4000
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4000/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
      interval: 3s
      timeout: 5s
      retries: 10
  products:
    image: '${DOCKER_REGISTRY}subgraph-v2-products${DOCKER_TAG}'
    container_name: v2-products
    networks:
      - test
    ports:
      - "0.0.0.0:4003:4003"
    environment:
      APOLLO_PORT: 4003
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4003/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
      interval: 3s
      timeout: 5s
      retries: 10
  reviews:
    image: '${DOCKER_REGISTRY}subgraph-v2-reviews${DOCKER_TAG}'
    container_name: v2-reviews
    networks:
      - test
    ports:
      - 4004:4000
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4000/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
      interval: 3s
      timeout: 5s
      retries: 10
  pandas:
    image: '${DOCKER_REGISTRY}subgraph-v2-pandas${DOCKER_TAG}'
    container_name: v2-pandas
    networks:
      - test
    ports:
      - "0.0.0.0:4005:4005"
    environment:
      APOLLO_PORT: 4005
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4005/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
      interval: 3s
      timeout: 5s
      retries: 10
        
networks:
  test:
    name: test-v2