version: '3.8'

services:
  users:
    build:
      context: ${BASE_DIR:-.}/../../subgraphs/users
      dockerfile: ./Dockerfile
  inventory:
    build:
      context: ${BASE_DIR:-.}/../../subgraphs/inventory
      dockerfile: ./Dockerfile
  products:
    build:
      context: ${BASE_DIR:-.}/../../subgraphs/products
      dockerfile: ./Dockerfile
  reviews:
    build:
      context: ${BASE_DIR:-.}/../../subgraphs/reviews
      dockerfile: ./Dockerfile
  pandas:
    build:
      context: ${BASE_DIR:-.}/../../subgraphs/pandas
      dockerfile: ./Dockerfile

networks:
  test:
    name: test-v2