services:
  accounts:
    build:
      context: ./accounts
      dockerfile: ../Dockerfile.rust
    environment:
      - PORT=4001
    ports:
      - 4001:4001
  inventory:
    build:
      context: ./inventory
      dockerfile: ../Dockerfile.rust
    environment:
      - PORT=4002
    ports:
      - 4002:4002
  products:
    build:
      context: ./products
      dockerfile: ../Dockerfile.rust
    environment:
      - PORT=4003
    ports:
      - 4003:4003
  reviews:
    build:
      context: ./reviews
      dockerfile: ../Dockerfile.rust
    environment:
      - PORT=4004
    ports:
      - 4004:4004

networks:
  test:
    name: test
