sources:
  - name: accounts
    handler:
      graphql:
        source: ../mesh/config/accounts.graphql
        endpoint: http://accounts:4001/graphql
  - name: inventory
    handler:
      graphql:
        source: ../mesh/config/inventory.graphql
        endpoint: http://inventory:4002/graphql
  - name: products
    handler:
      graphql:
        source: ../mesh/config/products.graphql
        endpoint: http://products:4003/graphql
  - name: reviews
    handler:
      graphql:
        source: ../mesh/config/reviews.graphql
        endpoint: http://reviews:4004/graphql

