name: fed-v1-constants-vus-subgraphs-delay-resources
on:
  pull_request: {}
  workflow_dispatch: {}
      
concurrency:
  group: fed-v1-constants-vus-subgraphs-delay-resources-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.template.yaml

  benchmark:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        directory: 
          - mesh
          - mesh-bun
          - apollo-server
          # - apollo-server-node16
          - apollo-router
          - mercurius
          - wundergraph
    uses: ./.github/workflows/benchmark.template.yaml
    name: ${{ matrix.directory }}
    with:
      gateway: ${{ matrix.directory }}
      vu: ${{ github.event_name == 'pull_request' && 100 || 350 }}
      time: ${{ github.event_name == 'pull_request' && '30s' || '400s' }}
      scenarioDir: scenarios/fed-v1-constants-vus-subgraphs-delay-resources
      runner: ${{ needs.setup.outputs.runner }}
      cpuLimit: '2'
      memoryLimit: '2gb'

  report:
    needs: benchmark
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioDir: scenarios/fed-v1-constants-vus-subgraphs-delay-resources
