name: fed-v1-ramping-vus
on:
  pull_request: {}
  workflow_dispatch: {}
      
concurrency:
  group: fed-v1-ramping-vus-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.template.yaml

  benchmark:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        directory: 
          - mesh
          - mesh-supergraph
          - mesh-bun
          - apollo-server
          # - apollo-server-node16
          # - apollo-gateway-with-yoga
          # - apollo-gateway-with-yoga-uws
          # - apollo-gateway-with-yoga-bun
          - apollo-router
          - mercurius
          - wundergraph
          # - stitching-federation-with-yoga
          # - stitching-federation-with-yoga-uws
          # - stitching-federation-with-yoga-deno
          # - stitching-federation-with-yoga-bun
    uses: ./.github/workflows/benchmark.template.yaml
    name: ${{ matrix.directory }}
    with:
      gateway: ${{ matrix.directory }}
      vu: ${{ github.event_name == 'pull_request' && 500 || 1500 }}
      time: ${{ github.event_name == 'pull_request' && '60s' || '300s' }}
      scenarioDir: scenarios/fed-v1-ramping-vus
      runner: ${{ needs.setup.outputs.runner }}
      cpuLimit: '2'
      memoryLimit: '2gb'
      
  report:
    needs: benchmark
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioDir: scenarios/fed-v1-ramping-vus