supergraph:
  path: /graphql
  listen: 0.0.0.0:4000
  introspection: true
traffic_shaping:
  all:
    deduplicate_query: true
sandbox:
  enabled: true
homepage:
  enabled: false
cors:
  allow_any_origin: true