on:
  workflow_call:
    inputs:
      hcl:
        type: string
        required: true
      dir:
        type: string
        required: true
      target:
        type: string
        required: true

jobs:
  bake:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: configure eqemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: 'linux/arm64,linux/amd64'

      - name: configure docker buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: login to docker registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker images
        timeout-minutes: 20
        id: docker-bake
        uses: docker/bake-action@4ba453fbc2db7735392b93edf935aaf9b1e8f747 # v6
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository }}/
          COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        with:
          source: .
          workdir: ${{ inputs.dir }}
          provenance: false
          push: true
          files: ${{ inputs.hcl }}
          targets: ${{ inputs.target }}
          set: |
            *.cache-from=type=gha,scope=build
            *.cache-to=type=gha,scope=build,mode=max