name: fed-v1-ramping-vus
on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  setup:
    uses: ./.github/workflows/setup.template.yaml

  benchmark:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        directory: [mesh, apollo-server, apollo-gateway-with-yoga, apollo-router, mercurius, wundergraph, stitching-federation-with-yoga, stitching-federation-with-yoga-deno, stitching-federation-with-yoga-bun]
    uses: ./.github/workflows/benchmark.template.yaml
    name: ${{ matrix.directory }}
    with:
      gateway: ${{ matrix.directory }}
      vu: 1000
      time: 60s
      scenarioDir: scenarios/fed-v1-ramping-vus
      runner: ${{ needs.setup.outputs.runner }}

  report:
    needs: benchmark
    uses: ./.github/workflows/report.template.yaml
    with:
      scenarioDir: scenarios/fed-v1-ramping-vus