name: fed-v1-constants-vus-subgraphs-delay
on:
  pull_request: {}
  push:
    branches:
      - 'main'

concurrency:
  group: fed-v1-constants-vus-subgraphs-delay-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.template.yaml

  benchmark:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        directory: 
          - mesh
          - mesh-bun
          - mesh-supergraph
          - apollo-server
          - apollo-server-node16
          - apollo-router
          - mercurius
          - wundergraph
    uses: ./.github/workflows/benchmark.template.yaml
    name: ${{ matrix.directory }}
    with:
      gateway: ${{ matrix.directory }}
      vu: ${{ github.event_name == 'pull_request' && 100 || 350 }}
      time: ${{ github.event_name == 'pull_request' && '30s' || '400s' }}
      scenarioDir: scenarios/fed-v1-constants-vus-subgraphs-delay
      runner: ${{ needs.setup.outputs.runner }}
      cpuLimit: ${{ github.event_name == 'pull_request' && '0.5' || '1' }}
      memoryLimit: ${{ github.event_name == 'pull_request' && '500mb' || '1gb' }}
      
  report:
    needs: benchmark
    uses: ./.github/workflows/report.template.yaml
    secrets: inherit
    with:
      scenarioDir: scenarios/fed-v1-constants-vus-subgraphs-delay
