version: '3.8'

services:
  gateway:
    image: gateway/wundergraph
    container_name: gateway
    networks:
      - test
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      # Added because we want to ensure 1 cpu is used, to make the comparison fair
      GOMAXPROCS: 1
    build:
      context: ${BASE_DIR:-.}/wundergraph
      dockerfile: ./Dockerfile
    depends_on:
      accounts: 
        condition: service_healthy
      inventory:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "-X", "POST", "-H" ,"Content-type: application/json", "http://localhost:4000/graphql", "--data-raw", "{\"query\": \"query { __typename }\"}"]
        interval: 8s
        timeout: 5s
        retries: 5
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-1gb}
networks:
  test:
    name: test